[build]
  # Build command untuk static site
  command = "npm run build:static"
  # Directory hasil build
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

# Redirect semua routes ke index.html untuk SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
